# Generated by Django 4.2.4 on 2023-08-26 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites_album', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='private',
            field=models.BooleanField(default=1, verbose_name='Приватный альбом'),
            preserve_default=False,
        ),
    ]
