# Generated by Django 4.2.2 on 2023-07-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
