# Generated by Django 4.2.4 on 2023-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photos_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='private',
            field=models.BooleanField(blank=True, null=True, verbose_name='Приватное фото'),
        ),
    ]
