# Generated by Django 4.2.4 on 2023-08-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photos_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='uniq_url',
            field=models.CharField(default='', max_length=32, verbose_name='Уникальный url'),
            preserve_default=False,
        ),
    ]
